spring:
  datasource:
    # DB config, use druid source
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://atnetwork.ctyvhkiaoslp.ap-southeast-1.rds.amazonaws.com/postgres
    username: atnetwork
    password: atnetwork2023

    druid:
      # connection pool
      initial-size: 5
      min-idle: 5
      max-active: 20
      # max wait
      max-wait: 30000
      # available closing time interval
      time-between-eviction-runs-millis: 60000
      # list alive time in pool
      min-evictable-idle-time-millis: 300000
      validation-query: select '1' from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # Open PCCache, and config each cache size
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      # Config filter, and open stat and firewall
      filters: stat,wall
      # Spring AOP interception, like x.y.z.service.*, use multiple , for seperation
    #   aop-patterns: com.example.demo.service.*


      # WebStatFilter config
      web-stat-filter:
        enabled: true
        # filter rule
        url-pattern: /*
        # neglect filter rule
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      # StatViewServlet config
      stat-view-servlet:
        enabled: true
        # Address path math/druid, jump to StatViewServlet
        url-pattern: /druid/*
        # Config if able to rest
        reset-enable: false
        # Console uer and pwd
        login-username: root
        login-password: 123456
        # IP white list
        # allow: 127.0.0.1
        #　I blacklist
        # deny: 192.168.1.218

      # Config StatFilter
      filter:
        stat:
          log-slow-sql: true
